language: c++

os:
  - osx

compiler:
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xerces-c fox; fi
script:
  - cd sumo
  - make -f Makefile.cvs
  - export CPPFLAGS="$CPPFLAGS -I/opt/X11/include -I/usr/local/include"
  - export LDFLAGS="-L/opt/X11/lib -stdlib=libc++"
  - ./configure CXX=clang++ CXXFLAGS="-stdlib=libc++ -std=gnu++11" --with-xerces=/usr/local --with-proj-gdal=/usr/local --enable-debug 
  - make -j4
  - make install
  - make examples
  - export SUMO_HOME=`pwd`
  - (cd examples;_PWD=`pwd`;ls | while read i; do if [[ "$i" == "tools" ]]; then continue;fi;EXEC=$i;echo $i;cd $i;find . -type d | while read j;do echo $j;count=(`ls -1 $j/test.* 2>/dev/null | wc -l`);if [ $count != 0 ];then $_PWD/../bin/$EXEC $j/test.*;SUCCESS=$?;if [ $SUCCESS != 0 ]; then echo "An error occured";exit $SUCCESS;fi;fi;done;SUCCESS=$?;if [ $SUCCESS != 0 ]; then exit $SUCCESS ;fi;cd $_PWD;done;SUCCESS=$?;if [ $SUCCESS != 0 ]; then exit $SUCCESS;fi)

